behaviours:
  2vs2:
    trainer_type: poca
    summary_freq: 10000
    time_horizon: 100
    max_steps: 50000000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    init_path: None
    threaded: false

  hyperparameters:
    learning_rate: 0.0003
    batch_size: 2048
    buffer_size: 20480
    learning_rate_schedule: constant

    beta: 0.005
    epsilon: 0.2
    beta_schedule: constant
    epsilon_schedule: constant
    lambd: 0.95
    num_epoch: 3
    time_scale: 1.0

  network_settings:
    hidden_units: 512
    num_layers: 2
    normalize: true
    vis_encode_type: simple
    conditioning_type: hyper
    
  self_play:
    save_steps: 50000
    team_change: 200000
    swap_steps: 10000
    play_against_latest_model_ratio: 0.5
    window: 10
    